---
version: '3.7'
networks:
  host:
    name: host
    external: true

volumes:
  web:
  config:

services:
  # FRONTEND
  web-file:
    image: >-
      europe-west1-docker.pkg.dev/robotnik-5830-dev/internal/novnc:web-1.3.0-1
    volumes:
      - type: volume
        source: web
        target: /data/web
      - type: volume
        source: config
        target: /data/config

  webserver:
    image: >-
      europe-west1-docker.pkg.dev/robotnik-5830-dev/internal/nginx:1.22.1-alpine
    environment:
      NGINX_PORT: 80
      NGINX_SERVER: localhost
      WEBSITE_PATH: "/var/www/html/web"
      PHP_SERVER: phpserver
      PHP_PORT: 9000
    ports:
      - target: 80
        published: 6081
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web
      - type: volume
        source: config
        target: /etc/nginx/templates/

  phpserver:
    image: >-
      europe-west1-docker.pkg.dev/robotnik-5830-dev/internal/php:8.0.26-fpm-alpine3.16
    environment:
      WEBSOCKITY_PORT: 6080
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web

  # BACKEND
  websockify:
    image: >-
      europe-west1-docker.pkg.dev/robotnik-5830-dev/internal/websockify:backend-0.10.0-1
    networks:
      - host
    command: "6080 localhost:5900"
